In [1]:
import pandas as pd

In [2]:
df_JCcitibike_tripdata_a = pd.read_csv("JC-201806-citibike-tripdata.csv")
df_JCcitibike_tripdata_b = pd.read_csv("JC-201807-citibike-tripdata.csv")
df_JCcitibike_tripdata_c = pd.read_csv("JC-201808-citibike-tripdata.csv")

In [3]:
print(df_JCcitibike_tripdata_a)
print(df_JCcitibike_tripdata_b)
print(df_JCcitibike_tripdata_c)

       tripduration                 starttime                  stoptime  \
0               329  2018-06-01 07:07:00.2990  2018-06-01 07:12:30.2220
1               259  2018-06-01 08:24:43.8490  2018-06-01 08:29:03.8450
2               686  2018-06-01 09:17:49.5730  2018-06-01 09:29:16.1770
3               164  2018-06-01 09:44:00.4020  2018-06-01 09:46:44.6830
4               769  2018-06-01 09:59:28.7800  2018-06-01 10:12:18.6660
...             ...                       ...                       ...
40932          1227  2018-06-30 20:46:55.7500  2018-06-30 21:07:22.9730
40933          1219  2018-06-30 20:47:02.7610  2018-06-30 21:07:22.1720
40934          1227  2018-06-30 20:47:03.1250  2018-06-30 21:07:30.3560
40935           252  2018-06-30 21:13:35.6890  2018-06-30 21:17:48.5690
40936           652  2018-06-30 22:03:44.8150  2018-06-30 22:14:37.5310

       start station id start station name  start station latitude  \
0                  3183     Exchange Place               40.716247
1                  3183     Exchange Place               40.716247
2                  3183     Exchange Place               40.716247
3                  3183     Exchange Place               40.716247
4                  3183     Exchange Place               40.716247
...                 ...                ...                     ...
40932              3681           Grand St               40.715178
40933              3681           Grand St               40.715178
40934              3681           Grand St               40.715178
40935              3681           Grand St               40.715178
40936              3681           Grand St               40.715178

       start station longitude  end station id  end station name  \
0                   -74.033459            3276  Marin Light Rail
1                   -74.033459            3267      Morris Canal
2                   -74.033459            3202      Newport PATH
3                   -74.033459            3267      Morris Canal
4                   -74.033459            3203     Hamilton Park
...                        ...             ...               ...
40932               -74.037683            3209      Brunswick St
40933               -74.037683            3209      Brunswick St
40934               -74.037683            3209      Brunswick St
40935               -74.037683            3267      Morris Canal
40936               -74.037683            3199      Newport Pkwy

       end station latitude  end station longitude  bikeid    usertype  \
0                 40.714584             -74.042817   29513  Subscriber
1                 40.712419             -74.038526   26221  Subscriber
2                 40.727224             -74.033759   29266  Subscriber
3                 40.712419             -74.038526   29472  Subscriber
4                 40.727596             -74.044247   33679  Subscriber
...                     ...                    ...     ...         ...
40932             40.724176             -74.050656   29197  Subscriber
40933             40.724176             -74.050656   33633    Customer
40934             40.724176             -74.050656   26297  Subscriber
40935             40.712419             -74.038526   29482  Subscriber
40936             40.728745             -74.032108   29235  Subscriber

       birth year  gender
0            1991       1
1            1989       2
2            1990       1
3            1993       1
4            1977       1
...           ...     ...
40932        1979       2
40933        1969       0
40934        1987       2
40935        1979       2
40936        1982       1

[40937 rows x 15 columns]
       tripduration                 starttime                  stoptime  \
0              1234  2018-07-01 02:08:39.8920  2018-07-01 02:29:14.4890
1              1041  2018-07-01 02:09:07.5180  2018-07-01 02:26:28.8720
2              2308  2018-07-01 02:14:45.7400  2018-07-01 02:53:14.5970
3               767  2018-07-01 02:25:12.4020  2018-07-01 02:38:00.0510
4               151  2018-07-01 04:07:44.0520  2018-07-01 04:10:15.8010
...             ...                       ...                       ...
42263           993  2018-07-31 08:51:08.1240  2018-07-31 09:07:41.5700
42264           311  2018-07-31 10:15:37.0040  2018-07-31 10:20:48.0740
42265           795  2018-07-31 15:45:01.4740  2018-07-31 15:58:16.6240
42266           918  2018-07-31 16:06:19.5890  2018-07-31 16:21:37.9990
42267          1956  2018-07-31 18:06:02.2850  2018-07-31 18:38:38.9730

       start station id start station name  start station latitude  \
0                  3183     Exchange Place               40.716247
1                  3183     Exchange Place               40.716247
2                  3183     Exchange Place               40.716247
3                  3183     Exchange Place               40.716247
4                  3183     Exchange Place               40.716247
...                 ...                ...                     ...
42263              3694     Jackson Square               40.711130
42264              3694     Jackson Square               40.711130
42265              3694     Jackson Square               40.711130
42266              3694     Jackson Square               40.711130
42267              3694     Jackson Square               40.711130

       start station longitude  end station id       end station name  \
0                   -74.033459            3183         Exchange Place
1                   -74.033459            3183         Exchange Place
2                   -74.033459            3183         Exchange Place
3                   -74.033459            3183         Exchange Place
4                   -74.033459            3275         Columbus Drive
...                        ...             ...                    ...
42263               -74.078900            3211             Newark Ave
42264               -74.078900            3694         Jackson Square
42265               -74.078900            3225  Baldwin at Montgomery
42266               -74.078900            3195                Sip Ave
42267               -74.078900            3280            Astor Place

       end station latitude  end station longitude  bikeid    usertype  \
0                 40.716247             -74.033459   26306    Customer
1                 40.716247             -74.033459   29204    Customer
2                 40.716247             -74.033459   26234    Customer
3                 40.716247             -74.033459   26238  Subscriber
4                 40.718355             -74.038914   29204  Subscriber
...                     ...                    ...     ...         ...
42263             40.721525             -74.046305   26299  Subscriber
42264             40.711130             -74.078900   26201    Customer
42265             40.723659             -74.064194   26225  Subscriber
42266             40.730743             -74.063784   26187  Subscriber
42267             40.719282             -74.071262   26201  Subscriber

       birth year  gender
0            1969       0
1            1969       0
2            1969       0
3            1992       1
4            1972       1
...           ...     ...
42263        1991       2
42264        1969       0
42265        1961       1
42266        1986       2
42267        1982       2

[42268 rows x 15 columns]
       tripduration                 starttime                  stoptime  \
0               903  2018-08-01 06:40:33.3610  2018-08-01 06:55:37.1060
1                78  2018-08-01 08:21:00.1450  2018-08-01 08:22:18.6310
2               405  2018-08-01 08:43:52.5150  2018-08-01 08:50:37.6140
3               155  2018-08-01 09:48:24.9450  2018-08-01 09:51:00.9360
4               453  2018-08-01 12:15:35.1230  2018-08-01 12:23:08.8880
...             ...                       ...                       ...
44427           462  2018-08-25 16:17:05.8840  2018-08-25 16:24:48.5890
44428           636  2018-08-28 12:31:22.4380  2018-08-28 12:41:59.2110
44429           954  2018-08-30 08:08:18.9250  2018-08-30 08:24:13.7900
44430           920  2018-08-31 08:08:54.2450  2018-08-31 08:24:14.8890
44431          1017  2018-08-31 12:57:23.8390  2018-08-31 13:14:20.9290

       start station id start station name  start station latitude  \
0                  3183     Exchange Place               40.716247
1                  3183     Exchange Place               40.716247
2                  3183     Exchange Place               40.716247
3                  3183     Exchange Place               40.716247
4                  3183     Exchange Place               40.716247
...                 ...                ...                     ...
44427              3694     Jackson Square               40.711130
44428              3694     Jackson Square               40.711130
44429              3694     Jackson Square               40.711130
44430              3694     Jackson Square               40.711130
44431              3694     Jackson Square               40.711130

       start station longitude  end station id end station name  \
0                   -74.033459            3270  Jersey & 6th St
1                   -74.033459            3184      Paulus Hook
2                   -74.033459            3202     Newport PATH
3                   -74.033459            3275   Columbus Drive
4                   -74.033459            3273     Manila & 1st
...                        ...             ...              ...
44427               -74.078900            3194  McGinley Square
44428               -74.078900            3195          Sip Ave
44429               -74.078900            3183   Exchange Place
44430               -74.078900            3184      Paulus Hook
44431               -74.078900            3211       Newark Ave

       end station latitude  end station longitude  bikeid    usertype  \
0                 40.725289             -74.045572   29612  Subscriber
1                 40.714145             -74.033552   29791  Subscriber
2                 40.727224             -74.033759   29571  Subscriber
3                 40.718355             -74.038914   29504  Subscriber
4                 40.721651             -74.042884   33669  Subscriber
...                     ...                    ...     ...         ...
44427             40.725340             -74.067622   29544  Subscriber
44428             40.730743             -74.063784   29544  Subscriber
44429             40.716247             -74.033459   29526  Subscriber
44430             40.714145             -74.033552   33633  Subscriber
44431             40.721525             -74.046305   29288  Subscriber

       birth year  gender
0            1977       1
1            1975       1
2            1973       1
3            1971       1
4            1993       1
...           ...     ...
44427        1990       1
44428        1990       1
44429        1977       1
44430        1977       1
44431        1964       1

[44432 rows x 15 columns]

In [4]:
summerdf_all_rows = pd.concat([df_JCcitibike_tripdata_a,df_JCcitibike_tripdata_b,df_JCcitibike_tripdata_c])
summerdf_all_rows

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,329,2018-06-01 07:07:00.2990,2018-06-01 07:12:30.2220,3183,Exchange Place,40.716247,-74.033459,3276,Marin Light Rail,40.714584,-74.042817,29513,Subscriber,1991,1
1,259,2018-06-01 08:24:43.8490,2018-06-01 08:29:03.8450,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26221,Subscriber,1989,2
2,686,2018-06-01 09:17:49.5730,2018-06-01 09:29:16.1770,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29266,Subscriber,1990,1
3,164,2018-06-01 09:44:00.4020,2018-06-01 09:46:44.6830,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29472,Subscriber,1993,1
4,769,2018-06-01 09:59:28.7800,2018-06-01 10:12:18.6660,3183,Exchange Place,40.716247,-74.033459,3203,Hamilton Park,40.727596,-74.044247,33679,Subscriber,1977,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44427,462,2018-08-25 16:17:05.8840,2018-08-25 16:24:48.5890,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,29544,Subscriber,1990,1
44428,636,2018-08-28 12:31:22.4380,2018-08-28 12:41:59.2110,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29544,Subscriber,1990,1
44429,954,2018-08-30 08:08:18.9250,2018-08-30 08:24:13.7900,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29526,Subscriber,1977,1
44430,920,2018-08-31 08:08:54.2450,2018-08-31 08:24:14.8890,3694,Jackson Square,40.711130,-74.078900,3184,Paulus Hook,40.714145,-74.033552,33633,Subscriber,1977,1
44431,1017,2018-08-31 12:57:23.8390,2018-08-31 13:14:20.9290,3694,Jackson Square,40.711130,-74.078900,3211,Newark Ave,40.721525,-74.046305,29288,Subscriber,1964,1

In [5]:
summerdf_all_rows.to_csv("Datafile/Summer.csv", index=False, header=True)